# Generated by Django 5.2.17 on 2026-09-26 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offices", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("locked", "Locked")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("standard_working_days", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("calculated_at", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("standard_working_days", models.PositiveSmallIntegerField()),
                ("employed_working_days", models.PositiveSmallIntegerField()),
                ("absent_days", models.PositiveSmallIntegerField()),
                ("unpaid_leave_days", models.PositiveSmallIntegerField()),
                ("payable_days", models.PositiveSmallIntegerField()),
                ("base_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "overtime_method",
                    models.CharField(
                        choices=[
                            ("multiplier", "Multiplier of derived hourly base rate"),
                            ("flat", "Flat hourly rate"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "overtime_hourly_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("overtime_seconds", models.PositiveIntegerField()),
                ("overtime_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="staff.employee"
                    ),
                ),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrun",
                    ),
                ),
            ],
            options={
                "ordering": ["pay_run_id", "employee__employee_number"],
            },
        ),
        migrations.CreateModel(
            name="PaidOvertime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconds", models.PositiveIntegerField()),
                (
                    "overtime_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="offices.overtimerequest",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_items",
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "ordering": ["overtime_request_id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("monthly_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "overtime_method",
                    models.CharField(
                        choices=[
                            ("multiplier", "Multiplier of derived hourly base rate"),
                            ("flat", "Flat hourly rate"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "overtime_hourly_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_structures",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id", "-effective_from"],
            },
        ),
        migrations.AddField(
            model_name="payslip",
            name="salary_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.salarystructure",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="one_pay_run_per_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="pay_run_valid_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "locked"])),
                name="pay_run_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.UniqueConstraint(
                fields=("employee", "effective_from"),
                name="one_salary_structure_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_base__gt", 0)), name="salary_positive_base"
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("overtime_hourly_rate__isnull", True),
                        ("overtime_method", "multiplier"),
                        ("overtime_multiplier__gt", 0),
                    ),
                    models.Q(
                        ("overtime_hourly_rate__gt", 0),
                        ("overtime_method", "flat"),
                        ("overtime_multiplier__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="salary_consistent_overtime_terms",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("pay_run", "employee"), name="one_payslip_per_employee_run"
            ),
        ),
    ]
